#include <WiFi.h>
#include <ESPAsyncWebSrv.h>

//Using Code generated by chat GPT: https://chat.openai.com/c/9aa906d4-2eb7-4fb0-8c3f-b6966a2ca117

// Replace with your network credentials
const char* ssid = "ESP32-AP";
const char* password = "password";

// Define the GPIO pin connected to the LED
const int ledPin = 2;

// Create an instance of the web server
AsyncWebServer server(80);

void setup() {
  // Initialize the LED pin as an output
  pinMode(ledPin, OUTPUT);

  // Create an open network (no password) or change the password as needed
  WiFi.softAP(ssid, password);

  // Hardcoded IP address for the ESP32
  IPAddress apIP(192, 168, 4, 1);
  WiFi.softAPConfig(apIP, apIP, IPAddress(255, 255, 255, 0));

  // Route to turn the LED on
  server.on("/on", HTTP_GET, [](AsyncWebServerRequest *request){
    digitalWrite(ledPin, HIGH);
    request->send(200, "text/plain", "LED turned on");
  });

  // Route to turn the LED off
  server.on("/off", HTTP_GET, [](AsyncWebServerRequest *request){
    digitalWrite(ledPin, LOW);
    request->send(200, "text/plain", "LED turned off");
  });

  // Serve the HTML page for controlling the LED
  server.on("/", HTTP_GET, [](AsyncWebServerRequest *request){
    String html = "<html><body>";
    html += "<h1>ESP32 Manual Portal</h1>";
    html += "<a href='/on'><button>Turn On</button></a>&nbsp;";
    html += "<a href='/off'><button>Turn Off</button></a>";
    html += "<script src = "http://localhost/HenryDavidHolbenJournalAndNotebook/.UniversalFooterContent.js"></script>

  </body></html>";
    request->send(200, "text/html", html);
  });

  // Start the server
  server.begin();
}

void loop() {
  // Your code here (if any)
}
