// *************** Liquid crystal display related variables ***************
const LiquidCrystalDisplayVariablesSection = `
// This section of the code is generated by index.html using InitialCppVariables.js
static int scrollPosition = 0;
bool selectPressed = false; // Select button latch
static bool ReturnToStatusPage = false;
`;

// *************** Voltage Probe related variables ***************
const VoltageProbeSpecifications = `
// This section of the code is generated by index.html using InitialCppVariables.js
const float Resistor1 = 11100; //ohms
const float Resistor2 = 2210; //ohms
`;

// *************** Global Variables ***************
const GlobalVariables = `
// This section of the code is generated by index.html using InitialCppVariables.js
String DeviceName = "${DeviceName}";
String DeviceNameTemp = DeviceName;
float NominalVoltage = ${NominalVoltage};
float TempNominalVoltage = NominalVoltage;
float ShutOffVoltage = ${ShutOffVoltage};
float TempShutOffVoltage = ShutOffVoltage;
float TurnBackOnVoltage = ${TurnBackOnVoltage};
float TempTurnBackOnVoltage = TurnBackOnVoltage;
unsigned long OverrideDelay = ${OverrideDelay * 60000}; // milliseconds
unsigned long TempOverrideDelay = OverrideDelay;
unsigned long TimerOffset = ${TimerOffset * 1000}; // milliseconds
const int DisconnectBufferTime = ${ShutOffVoltageTimer}; // Number of seconds to add to Disconnect timer (minimum value)
int LanguageSetting = ${LanguageSetting};
int TempLanguageSetting = LanguageSetting;
int DeviceSetting = ${DeviceSelection};
int SelectedPage = 0;
int OutputState = 0;
const int MaximumEncoderPosition = 4;
bool OverrideDelayLatch = false;
int LastOverrideButtonState = HIGH;
bool OverridePressed = false;
bool OverrideWhileOffAllowed = true;
unsigned long MaxOverrideDelay = 90 * 60000; // puts limit of 90 minutes
int ReconnectDelay = 10000;
const int numReadings = 20; // Adjust the number of readings based on your preferences
float readings[numReadings]; // Array to store readings
int index = 0; // Index for storing new readings
static unsigned long StartTime = 0;
static unsigned long EndTime = 0;
static bool TimerHasStarted = false;
unsigned long OverrideCurrentTime = 0;
unsigned long OverrideEndTime = 0;
static bool OverrideTimerHasStarted = false;
static bool ReconnectTimerHasStarted = false;
`;

// *************** Timer-related variables ***************
const TimerRelatedVariables = `
// This section of the code is generated by index.html using InitialCppVariables.js
unsigned long previousMillis = 0;
unsigned long RolloverTime = (pow(2, 32) - 1); // Set an interval in milliseconds to ensure that millis() rollover is never an issue for more than 10 minutes
`;

// *************** Get Pin Assignments ***************
const GetPinAssignments = `
// This section of the code is generated by index.html using InitialCppVariables.js
int VoltageProbe = ${PinData[DeviceSelection - 1].VoltageProbe};
int lcdSDA = ${PinData[DeviceSelection - 1].lcdSDA};
int lcdSCL = ${PinData[DeviceSelection - 1].lcdSCL};
int EncoderCLK = ${PinData[DeviceSelection - 1].EncoderCLK};
int EncoderDT = ${PinData[DeviceSelection - 1].EncoderDT};
int EncoderSW = ${PinData[DeviceSelection - 1].EncoderSW};
int OverrideDelayButton = ${PinData[DeviceSelection - 1].OverrideDelayButton};
int OverrideLight = ${PinData[DeviceSelection - 1].OverrideLight};
int RelayOutput = ${PinData[DeviceSelection - 1].RelayOutput};
int InputUp = ${PinData[DeviceSelection - 1].InputUp};
int InputDown = ${PinData[DeviceSelection - 1].InputDown};
int InputRight = ${PinData[DeviceSelection - 1].InputRight};
int InputLeft = ${PinData[DeviceSelection - 1].InputLeft};
int InputSelect = ${PinData[DeviceSelection - 1].InputSelect};
`;



/*Encoder Related Global Variables*/const EncoderRelatedGlobalVariables =
      `\n`
      +
      `//*************** Encoder Related Global Variables: *************** this section of the code is generated by index.html using InitialCppVariables.js ***************`
      +
      `\n \n \t`
      +
      `Encoder myEncoder(2, 3);`
      +
      `\n \t`
      +
      `long oldPosition = -999;`
      +
      `\n \t`
      +
      `int EncoderDirection = 0;`
      +
      `\n \t`
      +
      `const int scrollThreshold = 5;`
      +
      `\n \t`
      +
      `int ChangeInPosition = 0;`
      +
      `\n \t`
      +
      `int EncoderSelectState = HIGH;`
      +
      `\n \t`
      +
      `static int lastEncoderSelectState = HIGH;`
      +
      `\n`
      ;


/*Button Related Global Variables*/const ButtonRelatedGlobalVariables =
      `\n` 
      +
      `//*************** Button Related Global Variables: *************** this section of the code is generated by index.html using InitialCppVariables.js ***************`
      +
      `\n \n \t`
      +
      `long oldPosition = -999;`
      +
      `\n \t`
      +
      `static int lastEncoderSelectState = HIGH;`
      +
      `\n`
      ;
