/*Turn off output*/const TurnOffOutputFunction =
                  `\n`
                  +
                  `//*************** Turn Off Output Function: *************** this section of the code is generated by index.html using OutputTogglingFunctions.js ***************`
                  +
                  `\n \n \t`
                  +
                  `void TurnOffOutput()`
                  +
                  `\n \t`
                  +
                  `{`
                  +
                  `\n \t \t`
                  +
                  `digitalWrite(RelayOutput, HIGH);  // sets the relay output off`
                  +                  
                  `\n \t \t`
                  +
                  `OutputState = 0;`
                  +
                  `\n \t`
                  +
                  `} //end of function, TurnOffOutput()`
                  +
                  `\n`
                  ;
/*Turn on output*/const TurnOnOutputFunction =
                  `\n`
                  +
                  `//*************** Turn On Output Function: *************** this section of the code is generated by index.html using OutputTogglingFunctions.js ***************`
                  +
                  `\n \n \t`
                  +
                  `void TurnOnOutput() `
                  +
                  `\n \t`
                  +
                  `{`
                  +
                  `\n \t \t`
                  +
                  `digitalWrite(RelayOutput, LOW);  // sets the relay output on`
                  +
                  `\n \t \t`
                  +
                  `OutputState = 1;`
                  +
                  `\n \t`
                  +
                  `} //end of function, TurnOnOutput()`
                  +
                  `\n`
                  ;