/*Relay Output Selected*/if(OutputSelection == 1)
{
     /*Turn off relay output*/var TurnOffOutputFunction =
          `\n`
          +
          `//*************** Turn Off Output Function Mechanical Relay Version: *************** this section of the code is generated by index.html using OutputTogglingFunctions.js ***************`
          +
          `\n \n \t`
          +
          `void TurnOffOutput()`
          +
          `\n \t`
          +
          `{`
          +
          `\n \t \t`
          +
          `digitalWrite(RelayOutput, HIGH);  // sets the relay output off`
          +     
          `\n \t \t`
          +
          `OutputState = 0;`
          +
          `\n \t`
          +
          `} //end of function, TurnOffOutput()`
          +
          `\n`
          ;
     
     /*Turn on relayoutput*/var TurnOnOutputFunction =
          `\n`
          +
          `//*************** Turn On Output Function Mechanical Relay Version: *************** this section of the code is generated by index.html using OutputTogglingFunctions.js ***************`
          +
          `\n \n \t`
          +
          `void TurnOnOutput() `
          +
          `\n \t`
          +
          `{`
          +
          `\n \t \t`
          +
          `digitalWrite(RelayOutput, LOW);  // sets the relay output on`
          +
          `\n \t \t`
          +
          `OutputState = 1;`
          +
          `\n \t`
          +
          `} //end of function, TurnOnOutput()`
          +
          `\n`
          ;
}// end if(OutputSelection == 1)

/*Inverter Control Selected*/if(OutputSelection == 2)
{
     /*Turn off Inverter*/var TurnOffOutputFunction =
          `\n`
          +
          `//*************** Turn Off Output Function Inverter Version: *************** this section of the code is generated by index.html using OutputTogglingFunctions.js ***************`
          +
          `\n \n \t`
          +
          `void TurnOffOutput()`
          +
          `\n \t`
          +
          `{`
          +
          `\n \t \t`
          +
          `digitalWrite(RelayOutput, HIGH);  // sets the relay output off`
          +     
          `\n \t \t`
          +
          `OutputState = 0;`
          +
          `\n \t`
          +
          `} //end of function, TurnOffOutput()`
          +
          `\n`
          ;
     
     /*Turn on Inverter*/var TurnOnOutputFunction =
          `\n`
          +
          `//*************** Turn On Output Function Inverter Version: *************** this section of the code is generated by index.html using OutputTogglingFunctions.js ***************`
          +
          `\n \n \t`
          +
          `void TurnOnOutput() `
          +
          `\n \t`
          +
          `{`
          +
          `\n \t \t`
          +
          `digitalWrite(RelayOutput, LOW);  // sets the relay output on`
          +
          `\n \t \t`
          +
          `OutputState = 1;`
          +
          `\n \t`
          +
          `} //end of function, TurnOnOutput()`
          +
          `\n`
          ;
}// end if(OutputSelection == 2)




