/*Relay Output Selected*/if(OutputSelection == 1)
{
     /*Turn off relay output*/var TurnOffOutputFunction =
          `\n`
          +
          `//*************** Turn Off Output Function Mechanical Relay Version: *************** this section of the code is generated by index.html using OutputTogglingFunctions.js ***************`
          +
          `\n \n \t`
          +
          `void TurnOffOutput()`
          +
          `\n \t`
          +
          `{`
          +
          `\n \t \t`
          +
          `digitalWrite(RelayOutput, HIGH);  // sets the relay output off`
          +     
          `\n \t \t`
          +
          `OutputState = 0;`
          +
          `\n \t`
          +
          `} //end of function, TurnOffOutput()`
          +
          `\n`
          ;
     
     /*Turn on relayoutput*/var TurnOnOutputFunction =
          `\n`
          +
          `//*************** Turn On Output Function Mechanical Relay Version: *************** this section of the code is generated by index.html using OutputTogglingFunctions.js ***************`
          +
          `\n \n \t`
          +
          `void TurnOnOutput() `
          +
          `\n \t`
          +
          `{`
          +
          `\n \t \t`
          +
          `digitalWrite(RelayOutput, LOW);  // sets the relay output on`
          +
          `\n \t \t`
          +
          `OutputState = 1;`
          +
          `\n \t`
          +
          `} //end of function, TurnOnOutput()`
          +
          `\n`
          ;
}// end if(OutputSelection == 1)

/*Inverter Control Selected*/if(OutputSelection == 2) //this is for turning off an inverter directly
{
     /*Turn off Inverter*/var TurnOffOutputFunction =
          `\n`
          +
          `\n \t`
          +
          `void TurnOffOutput()`
          +
          `\n \t`
          +
          `{`
        `\n \t`
        +
        `if(OutputState == 1)`
        +
        `\n \t`
        +
        `{`
        +
          `\n \t`
          +
          `Serial.println("Turning Off");`
          +
                  `\n \t`
     +
     `digitalWrite(RelayOutput, LOW);  // sets the relay output On for 3 Seconds`
     +
         `\n \t`
         +
         ` delay(3000);`
         +
          `\n \t`
          +
          `digitalWrite(RelayOutput, HIGH);         //Sets the relay output Off for 3 seconds, where HIGH is default state OFF`
          +
          `\n\t`
          +
          `OutputState = 0;`
          +
        `\n\t`
     +
     `}`
     +
          `\n\t`
     +
     `} //end of function, TurnOffOutput()`
    
    //*************** Turn On Output Function Mechanical Relay Version: *************** this section of the code is generated by index.html using OutputTogglingFunctions.js ***************
     
      
     
     /*Turn on Inverter*/var TurnOnOutputFunction =
          `\n`
          +
          `\n \t`
          +
          `void TurnOnOutput()`
          +
          `\n \t`
          +
          `{`
          +
                `\n \t`
                +
                `Serial.println("Turning On");`
    
                `\n \t`
                +
                `digitalWrite(RelayOutput, LOW);  // sets the relay output On for 3 Seconds`
        `\n \t`
        +
        `delay(3000);`
        `\n \t`
        +
        `digitalWrite(RelayOutput, HIGH);         //Sets the relay output Off for 3 seconds, where HIGH is default state OFF`
                `\n \t`
                +
                `OutputState = 1;`
          +
          `\n \t`
          +
          `} //end of function, TurnOnOutput()`
          ;

}// end if(OutputSelection == 2)`




