



/*Void Setup Buttons*/    var SetupFunctionButtons =
     `\n`
     +
     `//*************** Set Up Function Buttons: *************** this section of the code is generated by index.html using SetupFunctions.js ***************`
     +
     `\n \n \t`
     +
     `void setup()`
     +
     `\n \t`
     +
     `{`
     +
     `\n \t \t`
     +
     `lcd.init(); // initialize the lcd`
     +
     `\n \t \t`
     +
     `lcd.backlight();`
     +
     `\n \t \t`
     +
     `//Button Initialization` /*Button Initialization*/
     +
     `\n \t \t`
     +
     `pinMode(InputUp, INPUT_PULLUP);`
     +
     `\n \t \t`
     +
     `pinMode(InputDown, INPUT_PULLUP);`
     +
     `\n \t \t`
     +
     `pinMode(InputLeft, INPUT_PULLUP);`
     +
     `\n \t \t`
     +
     `pinMode(InputRight, INPUT_PULLUP);`
     +
     `\n \t \t`
     +
     `pinMode(InputSelect, INPUT_PULLUP);`
     +
     `\n \t \t`
     +
     `pinMode(OverrideDelayButton, INPUT_PULLUP);`
     +
     `\n \t \t`
     +
     `pinMode(OverrideLight, OUTPUT);`
     +
     `\n \t \t`
     +
     `pinMode(RelayOutput, OUTPUT);`
     +
     `\n \t \t`
     +
     `selectPressed = true;`  // Initialize the select button latch
     +
     `\n \t \t`
     +
     `Serial.begin(${PinData[DeviceSelection].BaudRate});`
     +
     `\n \t \t`
     +
     DetectFlashingMode
     +
     `\n \t`
     +
     `} //End of void setup`
     +
     `\n`
     ;

     console.log(PinData[DeviceSelection]);

/*Void Setup*/    var SetupFunctionEncoder =
     `\n`
     +
     `//*************** Set Up Function Encoder: *************** this section of the code is generated by index.html using SetupFunctions.js ***************`
     +
     `\n \n \t`
     +
     `void setup()`
     +
     `\n \t`
     +
     `{`
     +
     `\n \t \t`
     +
     `lcd.init(); // initialize the lcd`
     +
     `\n \t \t`
     +
     `lcd.backlight();`
     +
     `\n \t \t`
+
     `pinMode(OverrideDelayButton, INPUT_PULLUP);`
     +
     `\n \t \t`
     +
       `pinMode(OverrideLight, OUTPUT);`
       +
       `\n \t \t`
       +
     `pinMode(RelayOutput, OUTPUT);`
     +
     `\n \t \t`
     +
     `pinMode(EncoderSW, INPUT_PULLUP);`
     +
     `\n \t \t`
     +
     `selectPressed = true;`  // Initialize the select button latch
     +
     `\n \t \t`
     +
     `Serial.begin(9600);`
     +
     `\n \t \t`
     +
     DetectFlashingMode
     +
     `\n \t`
     +
     `} //End of void setup`
     +
     `\n`
     ;