     /*Void Loop*/var LoopFunctionStart =
     `\n`
     +
     `//*************** Void Loop Function Begining *************** this section of the code is generated by index.html using VoidLoop.js ***************`
     +
     `\n \n \t`
     +
     `void loop()`
     +
     `\n \t`
     +
     `{`
     +
     `\n \t \t`
     +
     `//Initalization of Variables`
     +
     `\n \t \t`
          +
     `int lastSwitchState;`
 	+
     `\n \t \t`
     +
     `int EncoderSelectState = digitalRead(EncoderSW);`
     +
     `\n \t \t`
 	+
     LatchesSection
     ;

/*Void Loop*/var LoopFunctionPages = 
        `\n`
        +
        `//*************** Void Loop LCD Page Toggling Section *************** this section of the code is generated by index.html using VoidLoop.js ***************`
        +
        `\n \n \t`
        +
        `//LCD Page Toggling`
        ;   
        
 
     LoopFunctionPages = LoopFunctionPages
     +
     `\n \t`
     +
     LowVoltageCheck
     +
     ReconnectVoltageCheck
     +
     `\n \t`
     +
     `//*************** Void Loop Function End *************** this section of the code is generated by index.html using VoidLoop.js ***************`
     +
     `\n \t` 
     +
     `} //End of Void Loop`
     +
     `\n`
     ;//end of arduinoCode constant
